spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/desktop/study/h2/jpashop
    username: sa
    password: 921013
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

